<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260212163110 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE access_rights (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, granted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, user_id INT NOT NULL, cursus_id INT DEFAULT NULL, lesson_id INT DEFAULT NULL, purchase_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F3EB4431A76ED395 ON access_rights (user_id)');
        $this->addSql('CREATE INDEX IDX_F3EB443140AEF4B9 ON access_rights (cursus_id)');
        $this->addSql('CREATE INDEX IDX_F3EB4431CDF80196 ON access_rights (lesson_id)');
        $this->addSql('CREATE INDEX IDX_F3EB4431558FBEB9 ON access_rights (purchase_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_cursus ON access_rights (user_id, cursus_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_lesson ON access_rights (user_id, lesson_id)');
        $this->addSql('CREATE TABLE certifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, validated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, user_id INT NOT NULL, theme_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3B0D76D5A76ED395 ON certifications (user_id)');
        $this->addSql('CREATE INDEX IDX_3B0D76D559027487 ON certifications (theme_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cert_user_theme ON certifications (user_id, theme_id)');
        $this->addSql('CREATE TABLE cursus (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, price INT NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, theme_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_255A0C359027487 ON cursus (theme_id)');
        $this->addSql('CREATE TABLE cursus_validations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, validated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, user_id INT NOT NULL, cursus_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_482348D3A76ED395 ON cursus_validations (user_id)');
        $this->addSql('CREATE INDEX IDX_482348D340AEF4B9 ON cursus_validations (cursus_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cv_user_cursus ON cursus_validations (user_id, cursus_id)');
        $this->addSql('CREATE TABLE lesson_validations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, validated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, user_id INT NOT NULL, lesson_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_40CBC404A76ED395 ON lesson_validations (user_id)');
        $this->addSql('CREATE INDEX IDX_40CBC404CDF80196 ON lesson_validations (lesson_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_lv_user_lesson ON lesson_validations (user_id, lesson_id)');
        $this->addSql('CREATE TABLE lessons (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, video_url VARCHAR(255) DEFAULT NULL, position INT NOT NULL, price INT NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, cursus_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3F4218D940AEF4B9 ON lessons (cursus_id)');
        $this->addSql('CREATE TABLE purchases (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, stripe_session_id VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, user_id INT NOT NULL, cursus_id INT DEFAULT NULL, lesson_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AA6431FE1A314A57 ON purchases (stripe_session_id)');
        $this->addSql('CREATE INDEX IDX_AA6431FEA76ED395 ON purchases (user_id)');
        $this->addSql('CREATE INDEX IDX_AA6431FE40AEF4B9 ON purchases (cursus_id)');
        $this->addSql('CREATE INDEX IDX_AA6431FECDF80196 ON purchases (lesson_id)');
        $this->addSql('CREATE TABLE themes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, slug VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_154232DE989D9B62 ON themes (slug)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, is_verified BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE access_rights ADD CONSTRAINT FK_F3EB4431A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_rights ADD CONSTRAINT FK_F3EB443140AEF4B9 FOREIGN KEY (cursus_id) REFERENCES cursus (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_rights ADD CONSTRAINT FK_F3EB4431CDF80196 FOREIGN KEY (lesson_id) REFERENCES lessons (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_rights ADD CONSTRAINT FK_F3EB4431558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchases (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE certifications ADD CONSTRAINT FK_3B0D76D5A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE certifications ADD CONSTRAINT FK_3B0D76D559027487 FOREIGN KEY (theme_id) REFERENCES themes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cursus ADD CONSTRAINT FK_255A0C359027487 FOREIGN KEY (theme_id) REFERENCES themes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cursus_validations ADD CONSTRAINT FK_482348D3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cursus_validations ADD CONSTRAINT FK_482348D340AEF4B9 FOREIGN KEY (cursus_id) REFERENCES cursus (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lesson_validations ADD CONSTRAINT FK_40CBC404A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lesson_validations ADD CONSTRAINT FK_40CBC404CDF80196 FOREIGN KEY (lesson_id) REFERENCES lessons (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lessons ADD CONSTRAINT FK_3F4218D940AEF4B9 FOREIGN KEY (cursus_id) REFERENCES cursus (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchases ADD CONSTRAINT FK_AA6431FEA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchases ADD CONSTRAINT FK_AA6431FE40AEF4B9 FOREIGN KEY (cursus_id) REFERENCES cursus (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchases ADD CONSTRAINT FK_AA6431FECDF80196 FOREIGN KEY (lesson_id) REFERENCES lessons (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE access_rights DROP CONSTRAINT FK_F3EB4431A76ED395');
        $this->addSql('ALTER TABLE access_rights DROP CONSTRAINT FK_F3EB443140AEF4B9');
        $this->addSql('ALTER TABLE access_rights DROP CONSTRAINT FK_F3EB4431CDF80196');
        $this->addSql('ALTER TABLE access_rights DROP CONSTRAINT FK_F3EB4431558FBEB9');
        $this->addSql('ALTER TABLE certifications DROP CONSTRAINT FK_3B0D76D5A76ED395');
        $this->addSql('ALTER TABLE certifications DROP CONSTRAINT FK_3B0D76D559027487');
        $this->addSql('ALTER TABLE cursus DROP CONSTRAINT FK_255A0C359027487');
        $this->addSql('ALTER TABLE cursus_validations DROP CONSTRAINT FK_482348D3A76ED395');
        $this->addSql('ALTER TABLE cursus_validations DROP CONSTRAINT FK_482348D340AEF4B9');
        $this->addSql('ALTER TABLE lesson_validations DROP CONSTRAINT FK_40CBC404A76ED395');
        $this->addSql('ALTER TABLE lesson_validations DROP CONSTRAINT FK_40CBC404CDF80196');
        $this->addSql('ALTER TABLE lessons DROP CONSTRAINT FK_3F4218D940AEF4B9');
        $this->addSql('ALTER TABLE purchases DROP CONSTRAINT FK_AA6431FEA76ED395');
        $this->addSql('ALTER TABLE purchases DROP CONSTRAINT FK_AA6431FE40AEF4B9');
        $this->addSql('ALTER TABLE purchases DROP CONSTRAINT FK_AA6431FECDF80196');
        $this->addSql('DROP TABLE access_rights');
        $this->addSql('DROP TABLE certifications');
        $this->addSql('DROP TABLE cursus');
        $this->addSql('DROP TABLE cursus_validations');
        $this->addSql('DROP TABLE lesson_validations');
        $this->addSql('DROP TABLE lessons');
        $this->addSql('DROP TABLE purchases');
        $this->addSql('DROP TABLE themes');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
